### ISSUE TITLE
next_i64 does not return an i64 on non-64bits platforms

### ISSUE THREAD

**Issue by Ten0** [AxlLind/easy_io#1]
The number is capped to the max capacity of an usize, obviously because all of these are based on `next_usize()`, when the implementation should be specific for `u/i64` cases.

Love the concept of the crate btw, but a little frustrating when the tests don't pass because of this ^^

**Comment by AxlLind** [comment]
Amazing, thanks for reporting! Fixed in 08fa18a

Also thanks for using the crate! 😄
