### ISSUE TITLE
Having print & println be generic on T: Display would be more practical

### ISSUE THREAD

**Issue by Ten0** [AxlLind/easy_io#2]
```rust
writeln!(w, "{}", x);
write!(w, "{} ", y);
```
is verbose, I'd rather write:
```rust
w.println(x);
w.print(y);
```

Note that since in programming contests we often need space-separated stuff, it would be cool to have, say `w.prints` for printing with space.
Also, since we have a buffer if we could say "oh btw replace the space I just wrote with a \n" that would be cool as well:
```rust
let v: Vec<...> = ...;
v.into_iter().for_each(|x| w.prints(x));
w.s2nl();
```

**Comment by AxlLind** [comment]
Thanks for the suggestions!

I really like making print functions generic on any `Display`, not sure why I didn't do that from the beginning. I also agree that a `prints` function would be nice. I'll add these for sure.

I'm not sure about the `s2nl` function, I would have to think about it a bit. In almost all cases doing `w.print('\n')` there instead would still be judged as a correct answer. This would lessen the complexity of this struct, the less public functions the better I think.

**Comment by AxlLind** [comment]
Added in 6568066

**Comment by Ten0** [comment]
Amazing reactivity! <3
I see the point. Some platforms though expect the exact right output. And I like to have it clean ^^ Guess i'll use an edited version for that part :)

**Comment by Ten0** [comment]
`w.print('\n')` is a bit verbose though.
In case you change your mind, here's my implementation for s2nl, which is meant to ensure that the last written character is a `\n`:
```rust
	pub fn s2nl(&mut self) {
		match self.buf.last_mut() {
			Some(last) => match *last {
				b' ' => *last = b'\n',
				b'\n' => {}
				_ => self.buf.push(b'\n'),
			},
			None => panic!("Buffer is empty"),
		}
	}
```
