### ISSUE TITLE
Reading large inputs through `next_char` causes panic

### ISSUE THREAD

**Issue by Ten0** [AxlLind/easy_io#3]
`consume` should not just increment the pointer but also make sure to re-fill the buffer, or call to `peek` should make sure we have not gone over the boundary yet.
This implementation relying on the fact that `has_more` is called between every of these calls opens the door for that sort of bug.

Having it on the consume side has the downside of not behaving nicely on first input, so I propose the following fix:
https://github.com/Ten0/EasyIO.rs/commit/103edf8f91cfcb6e87475c77db584a98de5f2379

**Comment by AxlLind** [comment]
Oh man, nice catch! This turned out to be because `consume_until` does a call to `peek` before checking that we have more data! This meant this bug applies to any of the next methods.

If the previous next call ended exactly when the buffer ends this would have happened on any next call. Crazy that I did not encounter this before 😅 Rewriting `consume_until` like this should fix it:

```Rust
loop {
  self.assert_has_more();
  if test(self.peek()) { return; }
  self.consume();
}
```

For performance reasons you really want to avoid as many buffer checks as possible, so I think I will keep the implementations of consume/peek as they are.

**Comment by AxlLind** [comment]
Fixed in 0128382

**Comment by Ten0** [comment]
Well I was pretty forced to catch it when my submission would runtime error x)
Since Codeforces does not show stderr and does not fully show large inputs though, I had a hard time locating the error.

About your fix, this implementation still relies on the fact that a `has_more` or a `consume_until` is called before any call to `peek`, so the door is still opened for creating a similar bug in the future, so I'd rather use my fix which has the `assert_has_more` within `peek`. It provides a safer interface that pretty much can't panic on a call to `peek`, and enabled me to remove all the `assert_has_more` that were called before `peek`.

**Comment by AxlLind** [comment]
Yeah, I get that reasoning. But putting it in `peek` requires an additional call to `has_more` in all loops. You would to one in peek and then an additional one to break the loop if it was the last input.

Reading input should never be a performance problem in competitive programming so I feel it's quite important to keep this crate as performant as possible. I would rather keep this solution and be more careful with checking this in the future. Now all calls to `peek` have a check before them.

**Comment by Ten0** [comment]
Said call to `has_more` costing ~3 CPU instructions (depending on inlining), it is most liklely neglictable compared to whatever operation we're already doing around it (like say, actually reading it from the standard input), but if that is your concern then you could have `peek` return an option and have an `assert_peek()` that is `peek().expect(""InputReader: Reached end of input!")` that you would use when you expect the buffer to be non-empty.
Depending on inlining again, this would hopefully lead to the same number of instructions.
